server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://114.215.89.91:3306/zhisheng_pro?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true
    username: root
    password: Bili881121
    driver-class-name: com.mysql.jdbc.Driver
 jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

entitymanager.packagesToScan: com.bili.finacialSystem